### ISSUE TITLE
failed to run demo in windows

### ISSUE THREAD

**Issue by zuixiaosanlang** [cvg/nice-slam#40]
(torch_1_x) D:\work\code\3d_reconstruction_ai\nice-slam-master>python -W ignore run.py configs/Demo/demo.yaml
INFO: The output folder is output/Demo
INFO: The GT, generated and residual depth/color images can be found under output/Demo/vis/
INFO: The mesh can be found under output/Demo/mesh/
INFO: The checkpoint can be found under output/Demo/ckpt/
Tracking Frame 0:   0%|▎                                                                                                                                                                                  | 1/500 [00:07<58:53,  7.08s/it]
Tracking Frame 1:   0%|▎                                                                                                                                                                                  | 1/500 [00:07<58:53,  7.08s/it]
Process Process-3:
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\NICE_SLAM.py", line 286, in coarse_mapping
    self.coarse_mapper.run()
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\Mapper.py", line 606, in run
    gt_c2w, self.keyframe_dict, self.keyframe_list, cur_c2w=cur_c2w)
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\Mapper.py", line 316, in optimize_map
    mask_c2w, key, val.shape[2:], gt_depth_np)
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\Mapper.py", line 118, in get_mask_from_c2w
    w2c = np.linalg.inv(c2w)
  File "<__array_function__ internals>", line 6, in inv
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\site-packages\numpy\linalg\linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\site-packages\numpy\linalg\linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
Process Process-2:
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\NICE_SLAM.py", line 276, in mapping
    self.mapper.run()
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\Mapper.py", line 606, in run
    gt_c2w, self.keyframe_dict, self.keyframe_list, cur_c2w=cur_c2w)
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\Mapper.py", line 316, in optimize_map
    mask_c2w, key, val.shape[2:], gt_depth_np)
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\Mapper.py", line 118, in get_mask_from_c2w
    w2c = np.linalg.inv(c2w)
  File "<__array_function__ internals>", line 6, in inv
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\site-packages\numpy\linalg\linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\site-packages\numpy\linalg\linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
Tracking Frame 1:   0%|▋                                                                                                                                                                                  | 2/500 [00:08<31:21,  3.78s/it]
Tracking Frame 2:   0%|▋                                                                                                                                                                                  | 2/500 [00:08<31:21,  3.78s/it]
Tracking Frame 2:   0%|▋                                                                                                                                                                                  | 2/500 [00:09<41:07,  4.95s/it]

Process Process-1:
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "E:\ProgramData\Anaconda3\envs\torch_1_x\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\NICE_SLAM.py", line 266, in tracking
    self.tracker.run()
  File "D:\work\code\3d_reconstruction_ai\nice-slam-master\src\Tracker.py", line 195, in run
    device).float().inverse()
RuntimeError: inverse_cuda: For batch 0: U(1,1) is zero, singular U.

**Comment by Zzh2000** [comment]
Sorry, we did not test on windows, we mainly use Linux ubuntu 20.04.
