### ISSUE TITLE
ValueError: Image size of 582400x436800 pixels is too large. It must be less than 2^16 in each direction.

### ISSUE THREAD

**Issue by colin-de** [cvg/nice-slam#59]
I got error when running the demo, could you pls give me some advice? thx!
```Got keys from plugin meta data ("webp")
QFactoryLoader::QFactoryLoader() checking directory path "/home/lwh/miniconda3/envs/nice-slam/bin/imageformats" ...
loaded library "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqgif.so"
loaded library "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqicns.so"
loaded library "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqico.so"
loaded library "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqjpeg.so"
loaded library "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqsvg.so"
loaded library "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqtga.so"
loaded library "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqtiff.so"
loaded library "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqwbmp.so"
loaded library "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqwebp.so"
Tracking Frame 50:  10%|█▌             | 50/500 [00:46<07:00,  1.07it/s]
Process Process-1:
Traceback (most recent call last):
  File "/home/lwh/miniconda3/envs/nice-slam/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/lwh/miniconda3/envs/nice-slam/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lwh/nice-slam/src/NICE_SLAM.py", line 266, in tracking
    self.tracker.run()
  File "/home/lwh/nice-slam/src/Tracker.py", line 230, in run
    idx, cam_iter, gt_depth, gt_color, camera_tensor, self.c, self.decoders)
  File "/home/lwh/nice-slam/src/utils/Visualizer.py", line 68, in vis
    fig.tight_layout()
  File "/home/lwh/miniconda3/envs/nice-slam/lib/python3.7/site-packages/matplotlib/figure.py", line 3159, in tight_layout
    renderer = get_renderer(self)
  File "/home/lwh/miniconda3/envs/nice-slam/lib/python3.7/site-packages/matplotlib/tight_layout.py", line 183, in get_renderer
    return canvas.get_renderer()
  File "/home/lwh/miniconda3/envs/nice-slam/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 417, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/home/lwh/miniconda3/envs/nice-slam/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 91, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 582400x436800 pixels is too large. It must be less than 2^16 in each direction.
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqgif.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqicns.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqico.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqjpeg.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqsvg.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqtga.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqtiff.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqwbmp.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/imageformats/libqwebp.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/iconengines/libqsvgicon.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/xcbglintegrations/libqxcb-glx-integration.so" 
QLibraryPrivate::unload succeeded on "/home/lwh/miniconda3/envs/nice-slam/plugins/platforms/libqxcb.so" 
QLibraryPrivate::unload succeeded on "Xcursor" (faked)
```

**Comment by Zzh2000** [comment]
I think there should be some problem with the matplotlib and its default backends. Maybe your default is not the same as ours. Please double-check the environment and configurations.
Normally people are able to run the demo after they install the environment using conda YAML file, no other operation is required.
